services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: mlops-model-service:local
    container_name: mlops-model-service-api
    ports:
      - "8000:8000"
    environment:
      - ENV=local
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_MODEL_URI=models:/mlops-fastapi-classifier/1
    depends_on:
      - mlflow
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: mlops-model-service-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: mlops-model-service-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile
    container_name: mlops-model-service-mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow-data:/mlflow
      - ./mlartifacts:/mlartifacts
    restart: unless-stopped